import path from "node:path";
import chalk from "chalk";
import fs from "fs-extra";
import { glob } from "glob";

export async function bridgeCommand() {
  const cwd = process.cwd();
  console.log(chalk.blue("\n🔗 Syncing AI Agent Bridge..."));

  const skillFiles = await glob(".agents/skills/**/SKILL.md", { cwd });

  if (skillFiles.length === 0) {
    console.log(
      chalk.yellow(
        "⚠️ No skills found to bridge. Install some with 'synax add <skill>'.",
      ),
    );
    return;
  }

  // 1. Build Consolidated Rules
  let consolidatedRules = "# AI Agent Rules (Auto-generated by Synax)\n\n";
  consolidatedRules += "## Special Instructions for Antigravity\n";
  consolidatedRules += "- Respect the project's Persistent Context.\n";
  consolidatedRules +=
    "- Follow framework-specific TDD and Clean Code patterns.\n\n";

  for (const skillFile of skillFiles) {
    const content = await fs.readFile(path.join(cwd, skillFile), "utf8");
    const skillName = path.dirname(skillFile).split("/").pop();
    consolidatedRules += `### Skill: ${skillName}\n${content}\n\n`;
  }

  // 2. Write to common agent files
  await fs.writeFile(path.join(cwd, ".cursorrules"), consolidatedRules);

  // Also create a file for Antigravity to easily pick up
  await fs.writeFile(path.join(cwd, "SYNAX_CONTEXT.md"), consolidatedRules);

  console.log(chalk.green(`\n✅ Bridge sync complete!`));
  console.log(chalk.dim("- Updated .cursorrules"));
  console.log(
    chalk.dim("- Updated SYNAX_CONTEXT.md (for Antigravity/General)"),
  );
}
